// All translatable strings for the portfolio site.
// Proper nouns (names, project names, locations, URLs) are NOT translated.

export const translations = {
  // Header
  nav: {
    projects: { en: "PROJECTS", es: "PROYECTOS" },
    aboutMe: { en: "ABOUT ME", es: "SOBRE M\u00CD" },
  },

  // About Section
  about: {
    sectionLabel: { en: "ABOUT", es: "SOBRE M\u00CD" },
    heading: {
      prefix: { en: "architecting ", es: "arquitectando " },
      products: { en: "products", es: "productos" },
      from: { en: " from ", es: " de " },
      zero: { en: "zero", es: "cero" },
      to: { en: " to ", es: " a " },
      one: { en: "one", es: "uno" },
    },
    bio1: {
      en: "Originally from Galicia and now based in Barcelona, I spent my career in the trenches of early-stage startups. I am finishing an MBA at",
      es: "Originario de Galicia y actualmente en Barcelona, he desarrollado mi carrera en las trincheras de startups en fase inicial. Estoy terminando un MBA en",
    },
    bio1End: {
      en: "to gain a broader perspective of the market and formally structure the skills I instinctively developed during my first years as a founder.",
      es: "para obtener una perspectiva m\u00E1s amplia del mercado y estructurar formalmente las habilidades que desarroll\u00E9 instintivamente durante mis primeros a\u00F1os como fundador.",
    },
    bio2: {
      en: "For me, building great products requires an absolute obsession with progress. I have lived through massive market shifts and scaled global teams under intense pressure. Through all of that volatility, my core driver has always been a deep sense of movement.",
      es: "Para m\u00ED, construir grandes productos requiere una obsesi\u00F3n absoluta con el progreso. He vivido cambios masivos de mercado y escalado equipos globales bajo una presi\u00F3n intensa. A trav\u00E9s de toda esa volatilidad, mi motor principal siempre ha sido un profundo sentido del movimiento.",
    },
    bio3: {
      en: "I thrive in the space between deep engineering and the end user. Operating right at that intersection is where I have the right tools to transform problems into value. My goal is always to take raw ideas and illusions and embed them in a scalable reality that connects with people.",
      es: "Prospero en el espacio entre la ingenier\u00EDa profunda y el usuario final. Operar justo en esa intersecci\u00F3n es donde tengo las herramientas adecuadas para transformar problemas en valor. Mi objetivo siempre es tomar ideas e ilusiones y plasmarlas en una realidad escalable que conecte con las personas.",
    },
    stats: {
      onChainVolume: { en: "ON-CHAIN VOLUME", es: "VOLUMEN ON-CHAIN" },
      capitalSecured: { en: "CAPITAL SECURED", es: "CAPITAL ASEGURADO" },
      revenueGenerated: { en: "REVENUE GENERATED", es: "INGRESOS GENERADOS" },
    },
    howIWork: { en: "HOW I WORK", es: "C\u00D3MO TRABAJO" },
    approach: [
      {
        title: { en: "Identify the Pain Point", es: "Identificar el Problema" },
        description: {
          en: "I analyze market gaps and user behavior to find exactly where competitors miss the hook. Instead of guessing, I pinpoint the precise pain point, then design mechanics that solve it directly. This turns early adopters into an organic growth engine.",
          es: "Analizo brechas de mercado y comportamiento del usuario para encontrar exactamente d\u00F3nde los competidores fallan. En lugar de adivinar, identifico el punto de dolor preciso y dise\u00F1o mec\u00E1nicas que lo resuelven directamente. Esto convierte a los early adopters en un motor de crecimiento org\u00E1nico.",
        },
      },
      {
        title: { en: "Validate the Loop", es: "Validar el Ciclo" },
        description: {
          en: "I prove utility first. Before writing complex code, I ship a functional core loop to solve that pain point immediately. I test the thesis with real users, ensuring the value actually exists before investing in heavy architecture.",
          es: "Primero demuestro la utilidad. Antes de escribir c\u00F3digo complejo, lanzo un ciclo funcional para resolver ese problema de inmediato. Pruebo la tesis con usuarios reales, asegurando que el valor existe antes de invertir en arquitectura pesada.",
        },
      },
      {
        title: { en: "Architect the Foundation", es: "Arquitectar la Base" },
        description: {
          en: "Once the signal is proven, I go deep. I refactor the prototype into a robust system where the frontend feels effortless and the backend is built to scale. I prioritize modularity, allowing real user data to reshape the product organically.",
          es: "Una vez probada la se\u00F1al, profundizo. Refactorizo el prototipo en un sistema robusto donde el frontend se siente fluido y el backend est\u00E1 construido para escalar. Priorizo la modularidad, permitiendo que los datos reales de los usuarios transformen el producto org\u00E1nicamente.",
        },
      },
      {
        title: { en: "Optimize the Performance", es: "Optimizar el Rendimiento" },
        description: {
          en: "I look beyond what users say to analyze what their behavior actually reveals. Using data-driven systems, I identify hidden friction and uncover new opportunities for growth. Through rigorous testing, I iterate on the product loops to ensure long-term stickiness.",
          es: "Voy m\u00E1s all\u00E1 de lo que dicen los usuarios para analizar lo que su comportamiento realmente revela. Usando sistemas basados en datos, identifico fricciones ocultas y descubro nuevas oportunidades de crecimiento. Mediante pruebas rigurosas, itero en los ciclos del producto para asegurar la retenci\u00F3n a largo plazo.",
        },
      },
    ],
    nowPlaying: { en: "NOW PLAYING", es: "REPRODUCIENDO" },
    soundQuote: {
      en: "Sound is another form of architecture\u2014it\u2019s about structure, space, and a flow that is always evolving.",
      es: "El sonido es otra forma de arquitectura\u2014se trata de estructura, espacio y un flujo que siempre est\u00E1 evolucionando.",
    },
    contact: { en: "CONTACT", es: "CONTACTO" },
    letsChat: {
      en: "Let\u2019s talk about what\u2019s next.",
      es: "Hablemos de lo que viene.",
    },
    connect: { en: "Connect", es: "Conectar" },
  },

  // Photo captions
  photoCaptions: {
    "SCHOOL SHOOTING": { en: "SCHOOL SHOOTING", es: "FOTO ESCOLAR" },
    "SPRING AT BARCELONA": { en: "SPRING AT BARCELONA", es: "PRIMAVERA EN BARCELONA" },
    "CIES ISLANDS": { en: "CIES ISLANDS", es: "ISLAS C\u00CDES" },
    "RANDOM SELFIE": { en: "RANDOM SELFIE", es: "SELFIE RANDOM" },
    "LIFETIME FRIEND": { en: "LIFETIME FRIEND", es: "AMIGO DE TODA LA VIDA" },
  },

  // Project Feed
  projectFeed: {
    fullCaseStudy: { en: "Full Case Study", es: "Caso Completo" },
    year: { en: "YEAR", es: "A\u00D1O" },
    product: { en: "PRODUCT", es: "PRODUCTO" },
  },

  // Project blurbs (ES translations)
  projectBlurbs: {
    gliquid: {
      en: "In a highly technical market, we realized that users will always pay a premium for convenience. Gliquid was built entirely on speed and user experience. By automating the most frustrating parts of trading into a seamless interface, we proved that prioritizing frictionless, intuitive design is the ultimate revenue driver.",
      es: "En un mercado altamente t\u00E9cnico, nos dimos cuenta de que los usuarios siempre pagar\u00E1n m\u00E1s por la comodidad. Gliquid se construy\u00F3 enteramente sobre velocidad y experiencia de usuario. Al automatizar las partes m\u00E1s frustrantes del trading en una interfaz fluida, demostramos que priorizar un dise\u00F1o intuitivo y sin fricci\u00F3n es el mejor generador de ingresos.",
    },
    "tierra-labs": {
      en: "What started as a consumer social app faced a hard reality: the model simply wasn't sustainable. Listening to the market, we executed a complete pivot from a high-friction B2C app into a B2B AI infrastructure. By building an automated support system for niche blockchain communities, we turned a struggling platform into a grant-winning AI protocol.",
      es: "Lo que empez\u00F3 como una app social para consumidores enfrent\u00F3 una dura realidad: el modelo simplemente no era sostenible. Escuchando al mercado, ejecutamos un pivote completo de una app B2C de alta fricci\u00F3n a una infraestructura de IA B2B. Al construir un sistema de soporte automatizado para comunidades blockchain de nicho, transformamos una plataforma en dificultades en un protocolo de IA ganador de grants.",
    },
    "baile-das-piranhas": {
      en: "A flagship music project bridging the gap between Atlanta Plugg, Northern California rap, and Brazilian culture. Beyond sound design, this album was a masterclass in managing creative chaos. We navigated intense studio sessions with industry heavyweights to capture pure, authentic energy and build a completely unique sound experience.",
      es: "Un proyecto musical insignia que conecta el Plugg de Atlanta, el rap del norte de California y la cultura brasile\u00F1a. M\u00E1s all\u00E1 del dise\u00F1o sonoro, este \u00E1lbum fue una masterclass en gestionar el caos creativo. Navegamos sesiones de estudio intensas con pesos pesados de la industria para capturar energ\u00EDa pura y aut\u00E9ntica y construir una experiencia sonora completamente \u00FAnica.",
    },
    "equilibre-finance": {
      en: "Born from the ashes of a ecosystem hack, we built an exchange designed to solve the industry's biggest flaw: mercenary capital. By securing powerful B2B partnerships before we even launched the app, we entirely bypassed the notorious cold start problem and built a highly sustainable, dominant liquidity engine.",
      es: "Nacido de las cenizas de un hackeo del ecosistema, construimos un exchange dise\u00F1ado para resolver el mayor defecto de la industria: el capital mercenario. Al asegurar potentes alianzas B2B antes incluso de lanzar la app, evitamos por completo el notorio problema de arranque en fr\u00EDo y construimos un motor de liquidez altamente sostenible y dominante.",
    },
    "hermes-defi": {
      en: "What started as a solo attempt to outsmart the market during the COVID lockdowns evolved into a premier financial hub. Driven by conviction, we built the architecture from scratch, scaled a global team, and secured heavy institutional backing to launch a massive decentralized exchange.",
      es: "Lo que empez\u00F3 como un intento en solitario de superar al mercado durante los confinamientos por COVID evolucion\u00F3 en un hub financiero de primer nivel. Impulsados por la convicci\u00F3n, construimos la arquitectura desde cero, escalamos un equipo global y aseguramos un fuerte respaldo institucional para lanzar un exchange descentralizado masivo.",
    },
  },

  // Project stat labels
  projectStatLabels: {
    "Transaction Volume": { en: "Transaction Volume", es: "Volumen de Transacciones" },
    "Fees Generated": { en: "Fees Generated", es: "Comisiones Generadas" },
    "Unique Wallets": { en: "Unique Wallets", es: "Wallets \u00DAnicas" },
    "AI Grant (Berachain)": { en: "AI Grant (Berachain)", es: "Grant de IA (Berachain)" },
    "Community Members": { en: "Community Members", es: "Miembros de la Comunidad" },
    "Brand Sales": { en: "Brand Sales", es: "Ventas de Marca" },
    "Organic Streams": { en: "Organic Streams", es: "Reproducciones Org\u00E1nicas" },
    "Collaborating Artists": { en: "Collaborating Artists", es: "Artistas Colaboradores" },
    "Live Shows": { en: "Live Shows", es: "Shows en Vivo" },
    "TVL Secured": { en: "TVL Secured", es: "TVL Asegurado" },
    "Annual Revenue (2023)": { en: "Annual Revenue (2023)", es: "Ingresos Anuales (2023)" },
    "KAVA Grant": { en: "KAVA Grant", es: "Grant de KAVA" },
    "Private Round": { en: "Private Round", es: "Ronda Privada" },
    "Person Global Team": { en: "Person Global Team", es: "Equipo Global" },
    "Project Revenue": { en: "Project Revenue", es: "Ingresos del Proyecto" },
  },

  // Product types
  productTypes: {
    "Decentralized Exchange": { en: "Decentralized Exchange", es: "Exchange Descentralizado" },
    "Social DeFi App": { en: "Social DeFi App", es: "App Social DeFi" },
    "Music Album": { en: "Music Album", es: "\u00C1lbum Musical" },
    "DeFi Suite": { en: "DeFi Suite", es: "Suite DeFi" },
  },

  // Project descriptions
  projectDescriptions: {
    gliquid: {
      en: "Gliquid is a next-generation decentralized exchange built for seamless token swaps and liquidity provision. The platform combines cutting-edge AMM technology with an intuitive user interface, enabling users to trade with minimal slippage and maximum efficiency across multiple blockchain networks.",
      es: "Gliquid es un exchange descentralizado de nueva generaci\u00F3n construido para intercambios de tokens y provisi\u00F3n de liquidez sin fricci\u00F3n. La plataforma combina tecnolog\u00EDa AMM de vanguardia con una interfaz de usuario intuitiva, permitiendo a los usuarios operar con m\u00EDnimo deslizamiento y m\u00E1xima eficiencia en m\u00FAltiples redes blockchain.",
    },
    "tierra-labs": {
      en: "Tierra Labs revolutionizes decentralized finance by combining social features with DeFi primitives. Users can follow top traders, share strategies, and participate in community-driven investment DAOs, all while maintaining full custody of their assets through smart contract integration.",
      es: "Tierra Labs revoluciona las finanzas descentralizadas combinando funciones sociales con primitivas DeFi. Los usuarios pueden seguir a los mejores traders, compartir estrategias y participar en DAOs de inversi\u00F3n comunitarias, manteniendo la custodia total de sus activos a trav\u00E9s de la integraci\u00F3n con smart contracts.",
    },
    "baile-das-piranhas": {
      en: "A vibrant fusion of Brazilian funk and global sounds, Baile Das Piranhas captures the energy and spirit of street parties with infectious rhythms and bold production. Featuring collaborations with artists across multiple continents, this album pushes the boundaries of contemporary Latin music.",
      es: "Una vibrante fusi\u00F3n de funk brasile\u00F1o y sonidos globales, Baile Das Piranhas captura la energ\u00EDa y el esp\u00EDritu de las fiestas callejeras con ritmos contagiosos y una producci\u00F3n audaz. Con colaboraciones de artistas de m\u00FAltiples continentes, este \u00E1lbum empuja los l\u00EDmites de la m\u00FAsica latina contempor\u00E1nea.",
    },
    "equilibre-finance": {
      en: "Equilibre Finance is a ve(3,3) decentralized exchange designed to provide deep liquidity and sustainable yields. The protocol incentivizes long-term liquidity provision through its innovative tokenomics model, creating a balanced ecosystem for traders and liquidity providers alike.",
      es: "Equilibre Finance es un exchange descentralizado ve(3,3) dise\u00F1ado para proporcionar liquidez profunda y rendimientos sostenibles. El protocolo incentiva la provisi\u00F3n de liquidez a largo plazo a trav\u00E9s de su modelo innovador de tokenomics, creando un ecosistema equilibrado para traders y proveedores de liquidez.",
    },
    "hermes-defi": {
      en: "Hermes Defi offers a comprehensive suite of decentralized financial tools including swapping, staking, and yield farming. Built on Harmony blockchain, Hermes provides users with fast, low-cost transactions while maintaining the security and transparency of decentralized infrastructure.",
      es: "Hermes Defi ofrece un conjunto completo de herramientas financieras descentralizadas que incluyen intercambio, staking y yield farming. Construido sobre la blockchain Harmony, Hermes proporciona a los usuarios transacciones r\u00E1pidas y de bajo costo manteniendo la seguridad y transparencia de la infraestructura descentralizada.",
    },
  },

  // Case study page
  caseStudyPage: {
    back: { en: "BACK", es: "VOLVER" },
    projectNotFound: { en: "Project not found", es: "Proyecto no encontrado" },
    backToHome: { en: "Back to home", es: "Volver al inicio" },
    dataSource: { en: "Data Source:", es: "Fuente de Datos:" },
  },

  // Case study section content translations
  caseStudySections: {
    gliquid: {
      sections: [
        // 01 The Mobilization
        { type: "heading", en: "01 The Mobilization", es: "01 La Movilizaci\u00F3n" },
        { type: "text", en: "By mid-2025, the crypto market had matured. The middle class of DeFi, the true power users, had migrated to HyperEVM, attracted by an ecosystem that was seeing exploding revenue and user incentives. Yet, the infrastructure was thin. Only two decentralized exchanges existed to serve this growing sector. I realized I held a strategic asset sitting idle: a V4 DEX license purchased from Algebra in 2023. The opportunity was undeniable.", es: "A mediados de 2025, el mercado crypto hab\u00EDa madurado. La clase media de DeFi, los verdaderos power users, hab\u00EDan migrado a HyperEVM, atra\u00EDdos por un ecosistema con ingresos explosivos e incentivos para usuarios. Sin embargo, la infraestructura era escasa. Solo exist\u00EDan dos exchanges descentralizados para servir a este sector en crecimiento. Me di cuenta de que ten\u00EDa un activo estrat\u00E9gico parado: una licencia de DEX V4 comprada a Algebra en 2023. La oportunidad era innegable." },
        { type: "text", en: "I didn\u2019t write a whitepaper. I mobilized my CTO, lead dev, and the Algebra team to deploy in days. We adopted a strategy of direct community engagement: building in public and shipping one feature every single day based on specific user requests. This created a dynamic, ever-evolving experience that kept users hooked. Key Opinion Leaders (KOLs) began to take notice, validating that we were early and we were right. Within 72 hours, we attracted $500,000 in TVL.", es: "No escrib\u00ED un whitepaper. Movilic\u00E9 a mi CTO, lead dev y al equipo de Algebra para desplegar en d\u00EDas. Adoptamos una estrategia de engagement directo con la comunidad: construyendo en p\u00FAblico y lanzando una funci\u00F3n cada d\u00EDa basada en peticiones espec\u00EDficas de usuarios. Esto cre\u00F3 una experiencia din\u00E1mica y en constante evoluci\u00F3n que manten\u00EDa enganchados a los usuarios. Los Key Opinion Leaders (KOLs) empezaron a fijarse, validando que \u00E9ramos early y ten\u00EDamos raz\u00F3n. En 72 horas, atrajimos $500,000 en TVL." },
        // 02 Designing Revenue
        { type: "heading", en: "02 Designing Revenue", es: "02 Dise\u00F1ando Ingresos" },
        { type: "text", en: "As we scaled to $1M in daily volume, we analyzed user behavior to solve the revenue puzzle. Using PostHog, we tracked user sessions (averaging 30+ mins/week) and discovered a specific pricing sensitivity: users hated paying fees on performance, but they were willing to pay for convenience.", es: "Al escalar a $1M en volumen diario, analizamos el comportamiento de los usuarios para resolver el puzzle de ingresos. Usando PostHog, rastreamos sesiones de usuarios (promediando 30+ mins/semana) y descubrimos una sensibilidad de precios espec\u00EDfica: los usuarios odiaban pagar comisiones por rendimiento, pero estaban dispuestos a pagar por comodidad." },
        { type: "text", en: "We slashed standard trading fees to become a highly competitive execution venue, but introduced specific fees on automated actions like one-click position unwinding. The result was immediate. Users effectively paid us to save them clicks. This strategy allowed us to generate 30\u201340% of our project cash flow from UX convenience alone, proving that monetization is a design challenge, not just a financial one.", es: "Redujimos las comisiones est\u00E1ndar de trading para convertirnos en un venue de ejecuci\u00F3n altamente competitivo, pero introdujimos comisiones espec\u00EDficas en acciones automatizadas como el cierre de posiciones en un click. El resultado fue inmediato. Los usuarios efectivamente nos pagaban por ahorrarles clicks. Esta estrategia nos permiti\u00F3 generar el 30\u201340% de nuestro flujo de caja solo por conveniencia de UX, demostrando que la monetizaci\u00F3n es un reto de dise\u00F1o, no solo financiero." },
        // 03 Masking Complexity
        { type: "heading", en: "03 Masking Complexity", es: "03 Enmascarando la Complejidad" },
        { type: "text", en: "By day 50, the platform was managing $7M in daily volume and had onboarded 5,000+ unique wallets.", es: "Para el d\u00EDa 50, la plataforma gestionaba $7M en volumen diario y hab\u00EDa incorporado m\u00E1s de 5,000 wallets \u00FAnicas." },
        { type: "text", en: "The core technical challenge was Concentrated Liquidity. Users needed to add liquidity within specific price ranges, a complex process that typically introduces significant friction. While our backend, provided by Algebra, was rigid to ensure maximum security and robustness, our frontend needed to be the opposite.", es: "El desaf\u00EDo t\u00E9cnico central era la Liquidez Concentrada. Los usuarios necesitaban a\u00F1adir liquidez dentro de rangos de precio espec\u00EDficos, un proceso complejo que t\u00EDpicamente introduce una fricci\u00F3n significativa. Mientras nuestro backend, proporcionado por Algebra, era r\u00EDgido para asegurar m\u00E1xima seguridad y robustez, nuestro frontend necesitaba ser lo contrario." },
        { type: "text", en: "We architected a UX that eliminated these frictions, giving users the feeling of interacting with a completely fluid and customizable product. We didn\u2019t just build a DEX; we built a layer that translated raw protocol constraints into a seamless trader and liquidity provider experience.", es: "Arquitectamos una UX que eliminaba estas fricciones, dando a los usuarios la sensaci\u00F3n de interactuar con un producto completamente fluido y personalizable. No solo construimos un DEX; construimos una capa que traduc\u00EDa las restricciones del protocolo en una experiencia fluida para traders y proveedores de liquidez." },
      ],
    },
    "tierra-labs": {
      sections: [
        { type: "heading", en: "01 The Lean Pivot", es: "01 El Pivote Lean" },
        { type: "text", en: "Leaving ETH CC Brussels in the summer of 2024, we were hungry for a fresh challenge. After three years of building DEXs, we were burnt out on pure finance. Spotting Berachain's massive testnet traction, we pivoted and initially bet on the emerging Social Finance trend.", es: "Saliendo de ETH CC Bruselas en el verano de 2024, est\u00E1bamos hambrientos de un nuevo reto. Despu\u00E9s de tres a\u00F1os construyendo DEXs, est\u00E1bamos agotados de las finanzas puras. Al detectar la tracci\u00F3n masiva de la testnet de Berachain, pivotamos y apostamos inicialmente por la tendencia emergente de Social Finance." },
        { type: "text", en: "We launched a mobile app abstracting Web3 for social investing, aggressively engineering a waitlist of 1,200+ users through influencers and gamification. But the data didn\u2019t lie. Despite the hype, the LTV/CAC ratio was upside down. Development costs were immense, and unit economics were unsustainable.", es: "Lanzamos una app m\u00F3vil abstrayendo Web3 para inversi\u00F3n social, generando agresivamente una lista de espera de m\u00E1s de 1,200 usuarios a trav\u00E9s de influencers y gamificaci\u00F3n. Pero los datos no ment\u00EDan. A pesar del hype, el ratio LTV/CAC estaba invertido. Los costes de desarrollo eran inmensos y la econom\u00EDa unitaria insostenible." },
        { type: "text", en: "Instead of burning cash, we applied Lean Startup principles. We killed the feature but preserved the asset: The Community. We leveraged our visual culture to launch a Fund Tokenization testnet product, a trending, rapidly deployable model. To finance the next phase, we sold a collectible NFT collection to our power users, generating $50,000 in seed capital to expand the team.", es: "En lugar de quemar capital, aplicamos principios de Lean Startup. Eliminamos la funci\u00F3n pero preservamos el activo: La Comunidad. Aprovechamos nuestra cultura visual para lanzar un producto de Tokenizaci\u00F3n de Fondos en testnet, un modelo trending y r\u00E1pidamente desplegable. Para financiar la siguiente fase, vendimos una colecci\u00F3n de NFTs coleccionables a nuestros power users, generando $50,000 en capital semilla para expandir el equipo." },
        { type: "heading", en: "02 The RAG Architecture", es: "02 La Arquitectura RAG" },
        { type: "text", en: "With the team expanded and the runway secured, we identified a critical gap while we continued to polish our new product. The AI Gold Rush was in full swing, yet niche blockchain projects suffered from poor customer support. Generic LLMs hallucinated when queried about specific protocol documentation.", es: "Con el equipo expandido y la financiaci\u00F3n asegurada, identificamos una brecha cr\u00EDtica mientras continu\u00E1bamos puliendo nuestro nuevo producto. La Fiebre del Oro de la IA estaba en pleno apogeo, pero los proyectos blockchain de nicho sufr\u00EDan de un soporte al cliente deficiente. Los LLMs gen\u00E9ricos alucinaban al ser consultados sobre documentaci\u00F3n espec\u00EDfica de protocolos." },
        { type: "text", en: "We engineered a Retrieval-Augmented Generation (RAG) system designed specifically for technical documentation, creating a pipeline where the system scraped and structured complex protocol docs into reliable truth sources. We then packaged this infrastructure as a White-Glove SDK, allowing projects to plug our AI agent into their documentation effortlessly with full brand customization.", es: "Dise\u00F1amos un sistema de Generaci\u00F3n Aumentada por Recuperaci\u00F3n (RAG) espec\u00EDficamente para documentaci\u00F3n t\u00E9cnica, creando un pipeline donde el sistema extra\u00EDa y estructuraba documentos complejos de protocolos en fuentes de verdad fiables. Luego empaquetamos esta infraestructura como un SDK White-Glove, permitiendo a los proyectos integrar nuestro agente de IA en su documentaci\u00F3n sin esfuerzo con personalizaci\u00F3n total de marca." },
        { type: "heading", en: "03 The Ecosystem Fit", es: "03 El Encaje en el Ecosistema" },
        { type: "text", en: "The shift from B2C Social to B2B Infrastructure changed everything. We moved from chasing low-value users to solving high-value pain points for protocols.", es: "El cambio de B2C Social a Infraestructura B2B lo cambi\u00F3 todo. Pasamos de perseguir usuarios de bajo valor a resolver problemas de alto valor para protocolos." },
        { type: "text", en: "The market validated the pivot immediately. We were featured on the [Dabit3 AI podcast on X](https://x.com/dabit3/status/1878622136203653332?s=20), the industry\u2019s leading show at the time, but the ultimate confirmation came from the chain itself. [Berachain awarded us a $150,000 Innovation Grant](https://blog.berachain.com/blog/request-for-broposal-update-applications), recognizing both our RAG infrastructure and our community strength. We closed the loop by taking the fund tokenization product to a Mainnet launch, capturing the attention of the entire ecosystem.", es: "El mercado valid\u00F3 el pivote inmediatamente. Fuimos presentados en el [podcast de IA de Dabit3 en X](https://x.com/dabit3/status/1878622136203653332?s=20), el programa l\u00EDder de la industria en ese momento, pero la confirmaci\u00F3n definitiva vino de la propia cadena. [Berachain nos otorg\u00F3 un Grant de Innovaci\u00F3n de $150,000](https://blog.berachain.com/blog/request-for-broposal-update-applications), reconociendo tanto nuestra infraestructura RAG como la fuerza de nuestra comunidad. Cerramos el ciclo llevando el producto de tokenizaci\u00F3n de fondos a un lanzamiento en Mainnet, capturando la atenci\u00F3n de todo el ecosistema." },
      ],
    },
    "baile-das-piranhas": {
      sections: [
        { type: "heading", en: "01 The Cultural Context", es: "01 El Contexto Cultural" },
        { type: "text", en: "After more than three years of producing tracks together under my alias [05shawty](https://open.spotify.com/intl-es/artist/5e7Q6fx3lSMwG1wdwEc65d), moving from Vigo to Madrid and occasionally to Salobre\u00F1a after [Brabo Dinovo](https://open.spotify.com/intl-es/artist/0s0vEPYb6t0sZ1D6CE4Mi0) signed with Vendicion gave us the resources to evolve. We realized we needed to build a cohesive universe with a very specific sonic and visual identity rather than just dropping isolated mixtapes.", es: "Despu\u00E9s de m\u00E1s de tres a\u00F1os produciendo tracks juntos bajo mi alias [05shawty](https://open.spotify.com/intl-es/artist/5e7Q6fx3lSMwG1wdwEc65d), mudarnos de Vigo a Madrid y ocasionalmente a Salobre\u00F1a despu\u00E9s de que [Brabo Dinovo](https://open.spotify.com/intl-es/artist/0s0vEPYb6t0sZ1D6CE4Mi0) firmara con Vendicion nos dio los recursos para evolucionar. Nos dimos cuenta de que necesit\u00E1bamos construir un universo cohesivo con una identidad sonora y visual muy espec\u00EDfica en lugar de simplemente soltar mixtapes aislados." },
        { type: "text", en: "I produced the instrumentals to blend two distinct styles. We took the raw, dark drum patterns of Sacramento/North California rap (influences like Young Slo-Be) and layered them with the sweet, bright, and highly harmonic melodies of the Plugg subgenre (MexikoDro, Pierre Bourne). This created a complex backdrop for Brabo's ironic, innocent brazilian portuguese vocal delivery.", es: "Produje los instrumentales para mezclar dos estilos distintos. Tomamos los patrones de bater\u00EDa crudos y oscuros del rap de Sacramento/Norte de California (influencias como Young Slo-Be) y los superpusimos con las melod\u00EDas dulces, brillantes y altamente arm\u00F3nicas del subg\u00E9nero Plugg (MexikoDro, Pierre Bourne). Esto cre\u00F3 un tel\u00F3n de fondo complejo para la entrega vocal ir\u00F3nica e inocente en portugu\u00E9s brasile\u00F1o de Brabo." },
        { type: "text", en: "We needed a symbol to tie the California aesthetic (palm trees, low-riders) to Brazil. We chose the kite. In Brazilian favelas, children use kites not for play, but to warn local factions that authorities are approaching. It is a symbol of lost innocence. I built and flew these kites for the album artwork, mapping the gritty reality of favela survival onto the American rap aesthetic.", es: "Necesit\u00E1bamos un s\u00EDmbolo para unir la est\u00E9tica californiana (palmeras, low-riders) con Brasil. Elegimos la cometa. En las favelas brasile\u00F1as, los ni\u00F1os usan cometas no para jugar, sino para avisar a las facciones locales de que las autoridades se acercan. Es un s\u00EDmbolo de la inocencia perdida. Constru\u00ED y vol\u00E9 estas cometas para el artwork del \u00E1lbum, mapeando la cruda realidad de la supervivencia en las favelas sobre la est\u00E9tica del rap americano." },
        { type: "heading", en: "02 Session Psychology", es: "02 Psicolog\u00EDa de Sesi\u00F3n" },
        { type: "text", en: "Because our sound was distinct, it attracted attention. Through our stylist and connector, [Wetty Boop](https://www.instagram.com/wettyboop), we secured sessions with top-tier national artists like Kaydy Kain, MDA, and West Dubai, alongside elite producers like Bexnil and Pochi. As an emerging producer in the room with million-stream artists, I had to treat the studio like a high-performance engine.", es: "Porque nuestro sonido era distinto, atrajo atenci\u00F3n. A trav\u00E9s de nuestra estilista y conectora, [Wetty Boop](https://www.instagram.com/wettyboop), conseguimos sesiones con artistas nacionales de primer nivel como Kaydy Kain, MDA y West Dubai, junto a productores de \u00E9lite como Bexnil y Pochi. Como productor emergente en la sala con artistas de millones de reproducciones, tuve que tratar el estudio como un motor de alto rendimiento." },
        { type: "text", en: "Applying the 80/20 rule means understanding that a studio session is a race against time and focus. If the momentum stops, the drop in energy shows up immediately in the vocal performance. Instead of building from scratch, I used curated song samples to set the vibe instantly, programming drums in real-time so the artist could start writing right away.", es: "Aplicar la regla 80/20 significa entender que una sesi\u00F3n de estudio es una carrera contra el tiempo y la concentraci\u00F3n. Si el momentum se detiene, la ca\u00EDda de energ\u00EDa aparece inmediatamente en la interpretaci\u00F3n vocal. En lugar de construir desde cero, usaba samples de canciones seleccionados para establecer el vibe instant\u00E1neamente, programando bater\u00EDas en tiempo real para que el artista pudiera empezar a escribir de inmediato." },
        { type: "text", en: "Maintaining that flow means being part producer, part psychologist. You have to push the artist to finish the verse on the spot, if they leave the studio without a finished song, it usually dies. To protect that energy, I never wasted time on tiny details while the artist waited. I made hype mixes on the fly with aggressive filters and compression so the demo hit hard in their car on the way home, making them think, \u201CI have to drop this\u201D.", es: "Mantener ese flujo significa ser parte productor, parte psic\u00F3logo. Tienes que empujar al artista a terminar el verso en el momento; si se van del estudio sin una canci\u00F3n terminada, normalmente muere. Para proteger esa energ\u00EDa, nunca perd\u00EDa tiempo en peque\u00F1os detalles mientras el artista esperaba. Hac\u00EDa mezclas hype al vuelo con filtros agresivos y compresi\u00F3n para que la demo golpeara duro en su coche camino a casa, haci\u00E9ndoles pensar: \u00ABTengo que sacar esto\u00BB." },
        { type: "heading", en: "03 The Engineering & Execution", es: "03 La Ingenier\u00EDa y Ejecuci\u00F3n" },
        { type: "text", en: "Creating the raw tracks was collaborative chaos, but finishing the album was an exercise in systematic isolation. Post-production took almost half a year as I spent months in the headphones, pushing the raw studio energy to its absolute technical limits. This was followed by a rigorous two-month mastering process in collaboration with [Wabii](https://www.instagram.com/wabiiwannadie) to lock in the final sound.", es: "Crear los tracks en bruto fue un caos colaborativo, pero terminar el \u00E1lbum fue un ejercicio de aislamiento sistem\u00E1tico. La postproducci\u00F3n tom\u00F3 casi medio a\u00F1o mientras pasaba meses con los auriculares puestos, llevando la energ\u00EDa cruda del estudio a sus l\u00EDmites t\u00E9cnicos absolutos. Esto fue seguido de un riguroso proceso de masterizaci\u00F3n de dos meses en colaboraci\u00F3n con [Wabii](https://www.instagram.com/wabiiwannadie) para cerrar el sonido final." },
        { type: "text", en: "Once the masters were delivered, we didn't just drop the files. I coordinated directly with [Honey Money](https://www.instagram.com/honey_money_records) management to execute a 2.5-month rollout strategy. This involved mapping out a strict grid of vertical and horizontal content, scheduling social media drops, and managing the logistical friction of a complex, multi-artist release pipeline.", es: "Una vez entregados los masters, no simplemente soltamos los archivos. Coordin\u00E9 directamente con la gesti\u00F3n de [Honey Money](https://www.instagram.com/honey_money_records) para ejecutar una estrategia de lanzamiento de 2.5 meses. Esto implic\u00F3 mapear una cuadr\u00EDcula estricta de contenido vertical y horizontal, programar lanzamientos en redes sociales y gestionar la fricci\u00F3n log\u00EDstica de un pipeline de lanzamiento complejo y multi-artista." },
        { type: "text", en: "The ultimate lesson of Baile Das Piranhas was knowing when to let go. When you handle the beat, the recording, the mix, and the master, it will never sound perfect to your own ears. I learned to trust the initial instinct, preserve the raw human energy we captured in the room, and ship the product.", es: "La lecci\u00F3n definitiva de Baile Das Piranhas fue saber cu\u00E1ndo soltar. Cuando manejas el beat, la grabaci\u00F3n, la mezcla y el master, nunca sonar\u00E1 perfecto a tus propios o\u00EDdos. Aprend\u00ED a confiar en el instinto inicial, preservar la energ\u00EDa humana cruda que capturamos en la sala y lanzar el producto." },
      ],
    },
    "equilibre-finance": {
      sections: [
        { type: "heading", en: "01 The ve(3,3) Thesis", es: "01 La Tesis ve(3,3)" },
        { type: "text", en: "Losing our previous project to the [$100 million Harmony chain](https://www.merklescience.com/blog/hack-track-analysis-of-harmonys-horizon-bridge-exploit) hack forced a hard reset. While the market was collapsing under the Luna and FTX scandals, I realized the prevailing DEX model was structurally broken. Platforms were issuing hyper-inflated tokens to attract Liquidity Providers (LPs), who would instantly dump the tokens to cover impermanent loss. This mercenary capital created a death spiral of zero liquidity, zero volume, and zero fees.", es: "Perder nuestro proyecto anterior por el [hackeo de $100 millones de la cadena Harmony](https://www.merklescience.com/blog/hack-track-analysis-of-harmonys-horizon-bridge-exploit) forz\u00F3 un reinicio total. Mientras el mercado colapsaba bajo los esc\u00E1ndalos de Luna y FTX, me di cuenta de que el modelo DEX predominante estaba estructuralmente roto. Las plataformas emit\u00EDan tokens hiperinflados para atraer a Proveedores de Liquidez (LPs), quienes instantaneamente vend\u00EDan los tokens para cubrir p\u00E9rdidas impermanentes. Este capital mercenario cre\u00F3 una espiral de muerte de cero liquidez, cero volumen y cero comisiones." },
        { type: "text", en: "The paradigm shift was ve(3,3), a circular economic model that democratized token issuances and distributed 100% of trading fees to users who locked their tokens for up to four years. It perfectly aligned the incentives of LPs, DEX token, and traders.", es: "El cambio de paradigma fue ve(3,3), un modelo econ\u00F3mico circular que democratiz\u00F3 las emisiones de tokens y distribu\u00EDa el 100% de las comisiones de trading a usuarios que bloqueaban sus tokens hasta por cuatro a\u00F1os. Alineaba perfectamente los incentivos de LPs, el token del DEX y los traders." },
        { type: "text", en: "Building this was incredibly difficult because there was almost zero documentation on how to execute it, so we spent months in the trenches. While operating with a lean squad of five, led technically by my CTO [Miguel Acu\u00f1a](https://www.linkedin.com/in/miguelangelacunareboreda/), I lived in spreadsheets reverse-engineering smart contracts, modeling emission schedules, and mapping user flows based on early prototypes.", es: "Construir esto fue incre\u00EDblemente dif\u00EDcil porque pr\u00E1cticamente no hab\u00EDa documentaci\u00F3n sobre c\u00F3mo ejecutarlo, as\u00ED que pasamos meses en las trincheras. Mientras oper\u00E1bamos con un equipo lean de cinco personas, liderado t\u00E9cnicamente por mi CTO [Miguel Acu\u00f1a](https://www.linkedin.com/in/miguelangelacunareboreda/), viv\u00ED en hojas de c\u00E1lculo haciendo ingenier\u00EDa inversa de smart contracts, modelando calendarios de emisi\u00F3n y mapeando flujos de usuario basados en prototipos tempranos." },
        { type: "heading", en: "02 Solving the Cold Start", es: "02 Resolviendo el Arranque en Fr\u00EDo" },
        { type: "text", en: "Code is useless without capital. The fatal flaw of any new DEX is the cold start problem, because without volume there are no fees, and without fees LPs won\u2019t deposit liquidity.", es: "El c\u00F3digo es in\u00FAtil sin capital. El defecto fatal de cualquier nuevo DEX es el problema de arranque en fr\u00EDo, porque sin volumen no hay comisiones, y sin comisiones los LPs no depositar\u00E1n liquidez." },
        { type: "text", en: "While the engineering team built the infrastructure, we turned the operation into a B2B sales war room. To bypass the cold start entirely, we aggressively pitched global DeFi protocols, proving how our ve(3,3) mechanics offered superior capital efficiency compared to traditional models. By launch day, we had secured 15 heavy-hitting partners with hard capital committed to the platform. We didn't just build a DEX\u2014we built a B2B liquidity marketplace.", es: "Mientras el equipo de ingenier\u00EDa constru\u00EDa la infraestructura, convertimos la operaci\u00F3n en una sala de guerra de ventas B2B. Para evitar el arranque en fr\u00EDo por completo, presentamos agresivamente a protocolos DeFi globales, demostrando c\u00F3mo nuestras mec\u00E1nicas ve(3,3) ofrec\u00EDan una eficiencia de capital superior comparada con modelos tradicionales. Para el d\u00EDa del lanzamiento, hab\u00EDamos asegurado 15 partners de peso con capital comprometido en la plataforma. No solo construimos un DEX\u2014construimos un marketplace de liquidez B2B." },
        { type: "text", en: "We then took our 15 committed partners and approached the KAVA Chain with a simple proposition, telling them we had the narrative, the partners, and the money on the table, and asking if they were going to amplify us. KAVA backed us entirely, providing over $200,000 in bootstrapping incentives.", es: "Luego tomamos a nuestros 15 partners comprometidos y nos acercamos a KAVA Chain con una propuesta simple, dici\u00E9ndoles que ten\u00EDamos la narrativa, los partners y el dinero sobre la mesa, y pregunt\u00E1ndoles si iban a amplificarnos. KAVA nos respald\u00F3 completamente, proporcionando m\u00E1s de $200,000 en incentivos de arranque." },
        { type: "heading", en: "03 Execution & The Black Swan Again", es: "03 Ejecuci\u00F3n y el Cisne Negro de Nuevo" },
        { type: "text", en: "The protocol exploded. We hit $50M+ TVL in one week, driving over $100M in total value to the KAVA ecosystem and generating over $330,000 in ARR in 2023. To sustain this momentum and reach beyond the hardcore DeFi niche, we aggressively overhauled the complex ve(3,3) UX by simplifying interaction loops, standardizing protocol documentation, and hosting weekly educational spaces.", es: "El protocolo explot\u00F3. Alcanzamos m\u00E1s de $50M en TVL en una semana, impulsando m\u00E1s de $100M en valor total al ecosistema KAVA y generando m\u00E1s de $330,000 en ARR en 2023. Para sostener este momentum y llegar m\u00E1s all\u00E1 del nicho hardcore de DeFi, renovamos agresivamente la compleja UX ve(3,3) simplificando los loops de interacci\u00F3n, estandarizando la documentaci\u00F3n del protocolo y organizando espacios educativos semanales." },
        { type: "text", en: "But just as the product reached maturity, we were hit by a systemic failure outside of our smart contracts again. In July 2023, the Multichain Bridge, which was KAVA\u2019s primary cross-chain bridge, suffered a [catastrophic exploit resulting in over $125 million in stolen assets](https://www.forbes.com/sites/digital-assets/2023/07/07/multichain-missing-120-million-of-cryptocurrencies-and-its-ceo-pulls-the-plug/). Because KAVA\u2019s ecosystem relied heavily on this provider, millions in value plummeted, and trust in the network evaporated overnight.", es: "Pero justo cuando el producto alcanz\u00F3 su madurez, fuimos golpeados por un fallo sist\u00E9mico fuera de nuestros smart contracts de nuevo. En julio de 2023, el Multichain Bridge, que era el bridge cross-chain principal de KAVA, sufri\u00F3 un [exploit catastr\u00F3fico que result\u00F3 en m\u00E1s de $125 millones en activos robados](https://www.forbes.com/sites/digital-assets/2023/07/07/multichain-missing-120-million-of-cryptocurrencies-and-its-ceo-pulls-the-plug/). Como el ecosistema de KAVA depend\u00EDa en gran medida de este proveedor, millones en valor cayeron en picado y la confianza en la red se evapor\u00F3 de la noche a la ma\u00F1ana." },
        { type: "text", en: "Having already lost Hermes to a bridge exploit, watching Equilibre fall to another massive cross-chain hack was a definitive wake-up call. We had proven our ability to execute at the application layer, but this second systemic failure confirmed that the underlying infrastructure of DeFi carried an unmanageable level of counterparty risk.", es: "Habiendo ya perdido Hermes por un exploit de bridge, ver caer a Equilibre por otro hackeo masivo cross-chain fue una llamada de atenci\u00F3n definitiva. Hab\u00EDamos demostrado nuestra capacidad de ejecuci\u00F3n en la capa de aplicaci\u00F3n, pero este segundo fallo sist\u00E9mico confirm\u00F3 que la infraestructura subyacente de DeFi conllevaba un nivel inmanejable de riesgo de contraparte." },
      ],
    },
    "hermes-defi": {
      sections: [
        { type: "heading", en: "01 The Shift from Player to Builder", es: "01 De Jugador a Constructor" },
        { type: "text", en: "I graduated with a business degree during the peak of the COVID pandemic and took a job as a web designer in Galicia. I spent my free hours trying to trade crypto with my modest salary, hoping to make life-changing money. Like most retail traders, my psychological discipline was lacking, and after losing my entire paycheck to a developer who drained a protocol, my perspective completely flipped. I realized I needed to stop being the liquidity and start being the architect.", es: "Me gradu\u00E9 con un t\u00EDtulo en empresa durante el pico de la pandemia de COVID y consegu\u00ED un trabajo como dise\u00F1ador web en Galicia. Pasaba mis horas libres intentando hacer trading de crypto con mi modesto salario, esperando ganar dinero que cambiara mi vida. Como la mayor\u00EDa de los traders retail, me faltaba disciplina psicol\u00F3gica, y despu\u00E9s de perder toda mi n\u00F3mina con un desarrollador que dren\u00F3 un protocolo, mi perspectiva cambi\u00F3 completamente. Me di cuenta de que necesitaba dejar de ser la liquidez y empezar a ser el arquitecto." },
        { type: "text", en: "Using my next salary, I hired freelance developers and started sketching UI designs entirely by hand. My 15-year-old brother helped me digest the technical code while I focused on the whitepaper, branding, and community building. We observed the market, reverse-engineered successful mechanics, and added our own user experience layer to capture the hype. We launched a simple $55,000 pre-sale to test the waters, and it sold out in under 12 hours. Overnight, we went from zero to managing real capital.", es: "Con mi siguiente salario, contrat\u00E9 desarrolladores freelance y empec\u00E9 a bocetar dise\u00F1os de UI completamente a mano. Mi hermano de 15 a\u00F1os me ayudaba a digerir el c\u00F3digo t\u00E9cnico mientras yo me enfocaba en el whitepaper, el branding y la construcci\u00F3n de comunidad. Observamos el mercado, hicimos ingenier\u00EDa inversa de mec\u00E1nicas exitosas y a\u00F1adimos nuestra propia capa de experiencia de usuario para capturar el hype. Lanzamos una preventa simple de $55,000 para tantear el terreno, y se agot\u00F3 en menos de 12 horas. De la noche a la ma\u00F1ana, pasamos de cero a gestionar capital real." },
        { type: "heading", en: "02 Scaling the Operation", es: "02 Escalando la Operaci\u00F3n" },
        { type: "text", en: "From there, it was a race to scale the protocol. We started on Polygon, but I quickly realized the strategic advantage of being a dominant player in a smaller ecosystem, which led us to pivot to the Harmony network. This move coincided with aggressively expanding our core team to include my long-time CTO Miguel, a Brazilian senior lead dev, an American COO, and a dedicated all around squad from Argentina. We maintained a strictly horizontal structure, focusing heavily on recruiting only top-tier developers and keeping them motivated with high compensation and flexible hours.", es: "A partir de ah\u00ED, fue una carrera para escalar el protocolo. Empezamos en Polygon, pero r\u00E1pidamente me di cuenta de la ventaja estrat\u00E9gica de ser un jugador dominante en un ecosistema m\u00E1s peque\u00F1o, lo que nos llev\u00F3 a pivotar a la red Harmony. Este movimiento coincidi\u00F3 con una expansi\u00F3n agresiva de nuestro equipo central para incluir a mi CTO de siempre Miguel, un senior lead dev brasile\u00F1o, un COO americano y un equipo polivalente dedicado de Argentina. Manten\u00EDamos una estructura estrictamente horizontal, enfocados en reclutar solo desarrolladores de primer nivel y mantenerlos motivados con alta compensaci\u00F3n y horarios flexibles." },
        { type: "text", en: "We didn\u2019t just ship code, we built a highly engaged community. We created public goods like investment tracking spreadsheets, hosted weekly gaming sessions, and shipped merchandise to our most active users. Our impact even extended into the physical world when we [used protocol funds to back a local bakery in Michigan](https://x.com/hermesdefi/status/1491571632887975943?s=20), financing them to distribute food to families facing hardship. On the B2B side, we hit the ground running at ETH Denver, directly lobbying the Harmony [foundation for grants](https://talk.harmony.one/t/hermes-defi-the-hermes-protocol/10339) and securing [validator nodes](https://staking.harmony.one/validators/mainnet/one1ac8yehqexdnam9yza4q4y3zwrkyhrf4hqcpqy5) to build deep trust within the network. As our treasury grew, we hired a former JP Morgan analyst to deploy delta-neutral strategies, optimizing our internal yield multipliers and safely managing our rising Assets Under Management.", es: "No solo lanz\u00E1bamos c\u00F3digo, construimos una comunidad altamente comprometida. Creamos bienes p\u00FAblicos como hojas de c\u00E1lculo de seguimiento de inversiones, organizamos sesiones semanales de gaming y enviamos merch a nuestros usuarios m\u00E1s activos. Nuestro impacto se extendi\u00F3 incluso al mundo f\u00EDsico cuando [usamos fondos del protocolo para apoyar una panader\u00EDa local en Michigan](https://x.com/hermesdefi/status/1491571632887975943?s=20), financiando la distribuci\u00F3n de comida a familias en dificultades. En el lado B2B, salimos a toda velocidad en ETH Denver, presionando directamente a la [fundaci\u00F3n Harmony por grants](https://talk.harmony.one/t/hermes-defi-the-hermes-protocol/10339) y asegurando [nodos validadores](https://staking.harmony.one/validators/mainnet/one1ac8yehqexdnam9yza4q4y3zwrkyhrf4hqcpqy5) para construir confianza profunda dentro de la red. A medida que crec\u00EDa nuestra tesorer\u00EDa, contratamos a un ex analista de JP Morgan para desplegar estrategias delta-neutral, optimizando nuestros multiplicadores de rendimiento internos y gestionando de forma segura nuestros crecientes Assets Under Management." },
        { type: "heading", en: "03 The Peak and The Reset", es: "03 El Pico y el Reinicio" },
        { type: "text", en: "Our growth metrics and deep community integration attracted serious venture capital attention. We pitched our most ambitious vision yet, which was a one-stop-shop decentralized exchange designed to monopolize liquidity on Harmony. We successfully closed a $550,000 funding round backed by [M6](https://medium.com/hermes-defi/hermes-defi-receives-a-175-000-investment-for-their-trader-focused-dex-launching-on-harmony-9f25dd99b6f7) and [Harmony](https://talk.harmony.one/t/hermes-defi-investment/12405), allowing us to scale into a global operation with 17 full-time employees across multiple time zones. To handle the immense pressure of running a massive protocol at 23 years old, I isolated myself in the Basque Country, working 14-hour days to ensure a flawless product launch.", es: "Nuestras m\u00E9tricas de crecimiento y la profunda integraci\u00F3n comunitaria atrajeron la atenci\u00F3n seria del capital de riesgo. Presentamos nuestra visi\u00F3n m\u00E1s ambiciosa hasta la fecha: un exchange descentralizado todo-en-uno dise\u00F1ado para monopolizar la liquidez en Harmony. Cerramos exitosamente una ronda de financiaci\u00F3n de $550,000 respaldada por [M6](https://medium.com/hermes-defi/hermes-defi-receives-a-175-000-investment-for-their-trader-focused-dex-launching-on-harmony-9f25dd99b6f7) y [Harmony](https://talk.harmony.one/t/hermes-defi-investment/12405), permiti\u00E9ndonos escalar a una operaci\u00F3n global con 17 empleados a tiempo completo en m\u00FAltiples zonas horarias. Para manejar la inmensa presi\u00F3n de dirigir un protocolo masivo a los 23 a\u00F1os, me aisl\u00E9 en el Pa\u00EDs Vasco, trabajando 14 horas diarias para asegurar un lanzamiento impecable." },
        { type: "text", en: "We shipped the highly anticipated DEX. But just weeks later, the entire ecosystem collapsed. In June 2022, [hackers compromised the Harmony Horizon bridge, stealing over $100 million](https://www.merklescience.com/blog/hack-track-analysis-of-harmonys-horizon-bridge-exploit) and completely draining the collateral that backed the network\u2019s assets. The exploit rendered the blockchain a ghost town practically overnight, destroying the economic viability of our protocol. With our revenue model shattered by an external macro failure, I was forced to scale down and close Hermes Defi, walking away with a brutal but foundational masterclass in scaling, leadership, and systemic risk.", es: "Lanzamos el esperado DEX. Pero solo semanas despu\u00E9s, todo el ecosistema colaps\u00F3. En junio de 2022, [hackers comprometieron el bridge Harmony Horizon, robando m\u00E1s de $100 millones](https://www.merklescience.com/blog/hack-track-analysis-of-harmonys-horizon-bridge-exploit) y drenando completamente el colateral que respaldaba los activos de la red. El exploit convirti\u00F3 la blockchain en un pueblo fantasma pr\u00E1cticamente de la noche a la ma\u00F1ana, destruyendo la viabilidad econ\u00F3mica de nuestro protocolo. Con nuestro modelo de ingresos destrozado por un fallo macro externo, me vi obligado a reducir y cerrar Hermes Defi, llev\u00E1ndome una brutal pero fundamental masterclass en escalado, liderazgo y riesgo sist\u00E9mico." },
      ],
    },
  },
} as const
